
---
- name: Update DNS IP address on all machines in the network
  hosts: all
  become: yes
  tasks:
    - name: Ensure the NetworkManager package is installed (for systems using NetworkManager)
      dnf:
        name: NetworkManager
        state: present
      when: ansible_facts['distribution'] in ['Fedora', 'RedHat', 'CentOS'] and ansible_facts['distribution_version'] | version('8', '>=')

    - name: Set DNS server IP address for systems using NetworkManager
      nmcli:
        conn_name: "{{ ansible_facts['default_ipv4']['interface'] }}"
        type: ethernet
        dns4: "8.8.8.8" # Replace with your desired DNS IP
      when: ansible_facts['distribution'] in ['Fedora', 'RedHat', 'CentOS'] and ansible_facts['distribution_version'] | version('8', '>=')

    - name: Backup and replace /etc/resolv.conf for systems not using NetworkManager
      block:
        - name: Backup current /etc/resolv.conf
          command: cp /etc/resolv.conf /etc/resolv.conf.bak
          become: yes

        - name: Replace DNS server IP address in /etc/resolv.conf
          lineinfile:
            path: /etc/resolv.conf
            regexp: '^nameserver'
            line: 'nameserver 8.8.8.8' # Replace with your desired DNS IP
            create: yes
          become: yes
      when: ansible_facts['distribution'] not in ['Fedora', 'RedHat', 'CentOS'] or ansible_facts['distribution_version'] | version('8', '<')

    - name: Restart network service to apply changes (NetworkManager)
      systemd:
        name: NetworkManager
        state: restarted
      when: ansible_facts['distribution'] in ['Fedora', 'RedHat', 'CentOS'] and ansible_facts['distribution_version'] | version('8', '>=')

    - name: Restart networking service for other systems
      systemd:
        name: networking
        state: restarted
      when: ansible_facts['distribution'] not in ['Fedora', 'RedHat', 'CentOS'] or ansible_facts['distribution_version'] | version('8', '<')